export const countries = [
  {
    id: "BR",
    nome: "Brasil",
    continente: "América do Sul",
    nivelDeRisco: "alto",
    resumoClimatico: "O Brasil apresenta seca severa no Norte e Nordeste e chuvas intensas no Sul durante eventos de El Niño. A Amazônia sofre com incêndios florestais e o nível dos rios cai drasticamente.",
    impactoDoElNino: "Seca prolongada na Amazônia e Nordeste; chuvas excessivas no Sul; aumento de queimadas; perdas agrícolas significativas em soja e milho.",
    regioesAfetadas: "Amazônia, Nordeste, Sul do Brasil, Pantanal",
    ameacas: ["seca", "queimadas", "enchentes", "agricultura"],
    impactoNaAgricultura: "Quedas de produtividade podem ocorrer na soja e no milho em áreas com estresse hídrico, enquanto o excesso de chuva pode atrasar colheitas no Sul.",
    impactoNaAgua: "Redução drástica do nível de rios na Amazônia; risco de racionamento no Nordeste; reservatórios do Sudeste sob pressão.",
    impactoNaTemperatura: "Temperaturas acima da média e ondas de calor mais frequentes podem ocorrer no Norte e Nordeste.",
    impactoNasChuvas: "Tendência de redução de chuva no Norte e Nordeste e aumento de chuva no Sul.",
    confianca: "Alta",
    lat: -14.24, lng: -51.93,
  },
  {
    id: "US",
    nome: "Estados Unidos",
    continente: "América do Norte",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño traz invernos mais úmidos ao sul dos EUA e condições mais secas e quentes no norte. A Califórnia tende a receber mais chuvas.",
    impactoDoElNino: "Aumento de tempestades no sul da Califórnia; invernos mais amenos no norte; seca no noroeste do Pacífico.",
    regioesAfetadas: "Califórnia, Sudeste, Meio-Oeste, Costa do Golfo",
    ameacas: ["enchentes", "calor", "agricultura"],
    impactoNaAgricultura: "Impacto misto: beneficia irrigação na Califórnia mas prejudica safras no Meio-Oeste com calor excessivo.",
    impactoNaAgua: "Aumento de precipitação no Sul melhora reservatórios; seca no Noroeste do Pacífico.",
    impactoNaTemperatura: "Invernos mais quentes no norte; temperaturas acima da média no Meio-Oeste no verão.",
    impactoNasChuvas: "Aumento significativo no sul; redução no noroeste.",
    confianca: "Alta",
    lat: 37.09, lng: -95.71,
  },
  {
    id: "CA",
    nome: "Canadá",
    continente: "América do Norte",
    nivelDeRisco: "moderado",
    resumoClimatico: "El Niño traz invernos mais amenos no oeste do Canadá e condições mistas no leste.",
    impactoDoElNino: "Invernos mais quentes e secos no oeste; menor acúmulo de neve nas Montanhas Rochosas; risco de incêndios florestais no verão.",
    regioesAfetadas: "Colúmbia Britânica, Pradarias, Ontário",
    ameacas: ["queimadas", "seca", "calor"],
    impactoNaAgricultura: "Menor disponibilidade de água para irrigação nas Pradarias; temporada de crescimento mais longa mas com risco de seca.",
    impactoNaAgua: "Redução do manto de neve nas Rochosas afeta abastecimento de água no verão.",
    impactoNaTemperatura: "Invernos mais amenos podem ocorrer no oeste canadense.",
    impactoNasChuvas: "Redução de neve no oeste; padrões variáveis no leste.",
    confianca: "Moderada",
    lat: 56.13, lng: -106.35,
  },
  {
    id: "MX",
    nome: "México",
    continente: "América do Norte",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño intensifica a seca no centro e sul do México, com possível aumento de chuvas no norte.",
    impactoDoElNino: "Seca severa no centro e sul; temporada de furacões menos ativa no Atlântico mas mais forte no Pacífico.",
    regioesAfetadas: "Centro do México, Yucatán, Noroeste, Costa do Pacífico",
    ameacas: ["seca", "calor", "agricultura"],
    impactoNaAgricultura: "Redução da produção de milho e feijão; estresse hídrico em culturas de temporal.",
    impactoNaAgua: "Crise hídrica em cidades grandes; reservatórios em níveis críticos.",
    impactoNaTemperatura: "Temperaturas acima da média e ondas de calor podem ocorrer em várias regiões.",
    impactoNasChuvas: "Redução relevante das chuvas pode ocorrer no centro e sul do país.",
    confianca: "Alta",
    lat: 23.63, lng: -102.55,
  },
  {
    id: "AR",
    nome: "Argentina",
    continente: "América do Sul",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño geralmente traz chuvas excessivas ao Litoral e Pampa Úmida, com enchentes frequentes.",
    impactoDoElNino: "Enchentes no Litoral; chuvas acima da média no Pampa; benefício parcial para agricultura mas com riscos de alagamento.",
    regioesAfetadas: "Litoral, Buenos Aires, Pampa, Patagônia",
    ameacas: ["enchentes", "agricultura", "chuva intensa"],
    impactoNaAgricultura: "Impacto misto: mais água disponível mas risco de perda de safra por excesso de chuva; favorece soja em anos moderados.",
    impactoNaAgua: "Rios Paraná e Uruguai com níveis elevados; risco de enchentes urbanas.",
    impactoNaTemperatura: "Verões mais quentes; ondas de calor mais intensas.",
    impactoNasChuvas: "Aumento relevante das chuvas pode ocorrer no Litoral e no Pampa.",
    confianca: "Alta",
    lat: -38.42, lng: -63.62,
  },
  {
    id: "CL",
    nome: "Chile",
    continente: "América do Sul",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño traz chuvas intensas ao centro do Chile, região normalmente semiárida.",
    impactoDoElNino: "Chuvas torrenciais no centro; deslizamentos de terra; enchentes em áreas urbanas; benefício para reservatórios.",
    regioesAfetadas: "Santiago, Região Central, Atacama, Costa",
    ameacas: ["enchentes", "chuva intensa"],
    impactoNaAgricultura: "Danos em vinhedos e fruticultura; melhora nos reservatórios para irrigação a longo prazo.",
    impactoNaAgua: "Reposição de reservatórios após anos de seca; risco de inundações.",
    impactoNaTemperatura: "Temperaturas ligeiramente mais amenas no verão.",
    impactoNasChuvas: "Aumento expressivo das chuvas pode ocorrer no centro do Chile.",
    confianca: "Alta",
    lat: -35.68, lng: -71.54,
  },
  {
    id: "PE",
    nome: "Peru",
    continente: "América do Sul",
    nivelDeRisco: "extremo",
    resumoClimatico: "O Peru é um dos países mais diretamente afetados pelo El Niño, com chuvas devastadoras na costa norte.",
    impactoDoElNino: "Chuvas torrenciais na costa norte; enchentes e deslizamentos; colapso da pesca de anchova; destruição de infraestrutura.",
    regioesAfetadas: "Costa Norte, Lima, Piura, Lambayeque, Ancash",
    ameacas: ["enchentes", "chuva intensa", "agricultura"],
    impactoNaAgricultura: "Destruição de culturas costeiras; perdas na pesca; impacto severo na cadeia alimentar marinha.",
    impactoNaAgua: "Inundações costeiras; destruição de sistemas de abastecimento; contaminação de água.",
    impactoNaTemperatura: "Aquecimento costeiro acentuado e águas oceânicas muito mais quentes podem ocorrer.",
    impactoNasChuvas: "A chuva pode aumentar de forma excepcional na costa norte durante eventos fortes.",
    confianca: "Muito Alta",
    lat: -9.19, lng: -75.02,
  },
  {
    id: "CO",
    nome: "Colômbia",
    continente: "América do Sul",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño causa seca severa na Colômbia, afetando geração hidrelétrica e agricultura.",
    impactoDoElNino: "Seca prolongada; risco de racionamento de energia; incêndios florestais; perda de safras de café.",
    regioesAfetadas: "Região Andina, Llanos, Costa do Caribe, Amazônia colombiana",
    ameacas: ["seca", "queimadas", "agricultura"],
    impactoNaAgricultura: "Queda na produção de café, arroz e flores; perda de pastagens.",
    impactoNaAgua: "A vazão dos rios pode cair, elevando o risco para abastecimento e geração hidrelétrica.",
    impactoNaTemperatura: "Temperaturas e noites mais quentes podem ocorrer.",
    impactoNasChuvas: "Redução expressiva das chuvas pode ocorrer em grande parte do território.",
    confianca: "Alta",
    lat: 4.57, lng: -74.30,
  },
  {
    id: "AU",
    nome: "Austrália",
    continente: "Oceania",
    nivelDeRisco: "extremo",
    resumoClimatico: "A Austrália sofre severamente com El Niño, que traz seca extrema e incêndios florestais devastadores.",
    impactoDoElNino: "Seca severa no leste; temporada catastrófica de incêndios; perda massiva de gado e safras; branqueamento de corais na Grande Barreira.",
    regioesAfetadas: "Nova Gales do Sul, Queensland, Victoria, Austrália Ocidental",
    ameacas: ["seca", "queimadas", "calor", "agricultura"],
    impactoNaAgricultura: "A produção de trigo, a pecuária e as pastagens podem sofrer perdas importantes sob estresse hídrico severo.",
    impactoNaAgua: "Reservatórios em níveis mínimos; restrições hídricas em cidades; rios secando.",
    impactoNaTemperatura: "Calor recorde e noites muito quentes podem ocorrer.",
    impactoNasChuvas: "Redução severa das chuvas pode ocorrer no leste australiano.",
    confianca: "Muito Alta",
    lat: -25.27, lng: 133.78,
  },
  {
    id: "NZ",
    nome: "Nova Zelândia",
    continente: "Oceania",
    nivelDeRisco: "moderado",
    resumoClimatico: "El Niño traz ventos mais frios do sul e condições mais secas no nordeste da Nova Zelândia.",
    impactoDoElNino: "Seca no nordeste; ventos mais fortes do sul/sudoeste; temperaturas mais baixas que o normal em algumas regiões.",
    regioesAfetadas: "Northland, Auckland, Bay of Plenty",
    ameacas: ["seca", "agricultura"],
    impactoNaAgricultura: "Redução na produção de laticínios e frutas no norte; estresse hídrico em pastagens.",
    impactoNaAgua: "Pressão sobre reservatórios no norte; fluxo reduzido em rios.",
    impactoNaTemperatura: "Variável; pode ser mais frio ou mais quente dependendo da região.",
    impactoNasChuvas: "Redução moderada das chuvas pode ocorrer no nordeste.",
    confianca: "Moderada",
    lat: -40.90, lng: 174.89,
  },
  {
    id: "CN",
    nome: "China",
    continente: "Ásia",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño intensifica enchentes no sul da China e seca no norte, com monções alteradas.",
    impactoDoElNino: "Enchentes devastadoras no vale do Yangtze; seca no norte; tufões mais intensos; ondas de calor recordes.",
    regioesAfetadas: "Sul da China, Vale do Yangtze, Norte da China, Costa leste",
    ameacas: ["enchentes", "seca", "calor", "agricultura"],
    impactoNaAgricultura: "Perdas em arroz no sul por enchentes; seca afeta trigo no norte; impacto bilionário.",
    impactoNaAgua: "Enchentes no sul; escassez no norte; assimetria hídrica agravada.",
    impactoNaTemperatura: "Verões mais quentes e ondas de calor prolongadas podem ocorrer.",
    impactoNasChuvas: "Aumento no sul; redução significativa no norte.",
    confianca: "Alta",
    lat: 35.86, lng: 104.20,
  },
  {
    id: "IN",
    nome: "Índia",
    continente: "Ásia",
    nivelDeRisco: "extremo",
    resumoClimatico: "El Niño pode enfraquecer a monção indiana e ampliar riscos de seca em áreas densamente povoadas.",
    impactoDoElNino: "Monção enfraquecida; seca agrícola severa; ondas de calor letais; crise alimentar potencial.",
    regioesAfetadas: "Rajastão, Maharashtra, Karnataka, Andhra Pradesh, Índia Central",
    ameacas: ["seca", "calor", "agricultura"],
    impactoNaAgricultura: "Arroz, trigo e culturas de sequeiro podem sofrer perdas quando a monção enfraquece, afetando comunidades agrícolas em grande escala.",
    impactoNaAgua: "Reservatórios em níveis críticos; crise de água potável; secagem de poços.",
    impactoNaTemperatura: "Ondas de calor extremas podem elevar riscos à saúde.",
    impactoNasChuvas: "A monção de verão pode apresentar redução relevante.",
    confianca: "Muito Alta",
    lat: 20.59, lng: 78.96,
  },
  {
    id: "JP",
    nome: "Japão",
    continente: "Ásia",
    nivelDeRisco: "moderado",
    resumoClimatico: "El Niño tende a trazer verões mais frescos e invernos mais amenos ao Japão.",
    impactoDoElNino: "Verões mais frescos e chuvosos; temporada de tufões alterada; invernos mais amenos.",
    regioesAfetadas: "Kyushu, Shikoku, Kanto, Hokkaido",
    ameacas: ["chuva intensa", "enchentes"],
    impactoNaAgricultura: "Verões mais frescos podem afetar produção de arroz; chuvas excessivas danificam colheitas.",
    impactoNaAgua: "Geralmente adequado; risco de enchentes localizadas.",
    impactoNaTemperatura: "Verões mais frescos e invernos mais amenos podem ocorrer.",
    impactoNasChuvas: "Aumento de chuvas no verão; padrões de tufão alterados.",
    confianca: "Moderada",
    lat: 36.20, lng: 138.25,
  },
  {
    id: "ID",
    nome: "Indonésia",
    continente: "Ásia",
    nivelDeRisco: "extremo",
    resumoClimatico: "A Indonésia é severamente afetada por El Niño com seca extrema e incêndios florestais massivos.",
    impactoDoElNino: "Seca extrema; incêndios florestais em Bornéu e Sumatra; poluição do ar transfronteiriça; perda de biodiversidade.",
    regioesAfetadas: "Kalimantan, Sumatra, Java, Sulawesi, Papua",
    ameacas: ["seca", "queimadas", "agricultura", "calor"],
    impactoNaAgricultura: "Queda severa na produção de arroz e óleo de palma; perda de safras em todo o arquipélago.",
    impactoNaAgua: "Seca severa; falta de água potável em áreas rurais; rios secando.",
    impactoNaTemperatura: "Temperaturas mais altas e umidade muito baixa podem ocorrer.",
    impactoNasChuvas: "Redução severa das chuvas pode ocorrer em grande parte do arquipélago.",
    confianca: "Muito Alta",
    lat: -0.79, lng: 113.92,
  },
  {
    id: "PH",
    nome: "Filipinas",
    continente: "Ásia",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño causa seca severa nas Filipinas, afetando agricultura e abastecimento de água.",
    impactoDoElNino: "Seca prolongada; redução da temporada de tufões; estresse hídrico severo; perdas agrícolas massivas.",
    regioesAfetadas: "Mindanao, Visayas, Luzon Central",
    ameacas: ["seca", "agricultura", "calor"],
    impactoNaAgricultura: "A produção de arroz pode cair de forma importante, com danos também em cana-de-açúcar e milho.",
    impactoNaAgua: "Racionamento de água em Manila e outras cidades; reservatórios em níveis mínimos.",
    impactoNaTemperatura: "Temperaturas e índice de calor muito elevados podem ocorrer.",
    impactoNasChuvas: "Redução expressiva das chuvas pode ocorrer em todo o arquipélago.",
    confianca: "Alta",
    lat: 12.88, lng: 121.77,
  },
  {
    id: "ZA",
    nome: "África do Sul",
    continente: "África",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño causa seca severa na África do Sul, agravando a crise hídrica existente.",
    impactoDoElNino: "Seca prolongada; crise no abastecimento de água; perdas na produção de milho; incêndios no bush.",
    regioesAfetadas: "Limpopo, KwaZulu-Natal, Free State, Western Cape",
    ameacas: ["seca", "agricultura", "queimadas", "calor"],
    impactoNaAgricultura: "Milho e pecuária podem sofrer perdas, com pressão sobre os preços de alimentos.",
    impactoNaAgua: "Barragens em níveis críticos; racionamento em cidades; crise de Day Zero.",
    impactoNaTemperatura: "Temperaturas acima da média e ondas de calor mais frequentes podem ocorrer.",
    impactoNasChuvas: "Redução expressiva das chuvas de verão pode ocorrer.",
    confianca: "Alta",
    lat: -30.56, lng: 22.94,
  },
  {
    id: "EG",
    nome: "Egito",
    continente: "África",
    nivelDeRisco: "moderado",
    resumoClimatico: "El Niño pode afetar indiretamente o Egito através de mudanças no Nilo e ondas de calor.",
    impactoDoElNino: "Alteração na vazão do Nilo; ondas de calor mais intensas; impacto na agricultura do delta.",
    regioesAfetadas: "Delta do Nilo, Cairo, Alto Egito",
    ameacas: ["calor", "seca", "agricultura"],
    impactoNaAgricultura: "Impacto na irrigação do delta; estresse térmico em culturas; aumento na demanda de água.",
    impactoNaAgua: "Possível redução na vazão do Nilo; estresse hídrico urbano.",
    impactoNaTemperatura: "Ondas de calor extremas e noites mais quentes podem ocorrer.",
    impactoNasChuvas: "Impacto mínimo direto; efeito indireto via Nilo.",
    confianca: "Moderada",
    lat: 26.82, lng: 30.80,
  },
  {
    id: "NG",
    nome: "Nigéria",
    continente: "África",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño afeta a temporada de chuvas na Nigéria, com seca no norte e enchentes no sul.",
    impactoDoElNino: "Seca no Sahel nigeriano; enchentes no delta do Níger; perda de safras; deslocamento de populações.",
    regioesAfetadas: "Norte da Nigéria, Delta do Níger, Lagos, Zona Central",
    ameacas: ["seca", "enchentes", "agricultura"],
    impactoNaAgricultura: "Redução na produção de milho, sorgo e amendoim no norte; enchentes destroem plantações no sul.",
    impactoNaAgua: "Seca no norte; enchentes no sul; contaminação de fontes de água.",
    impactoNaTemperatura: "Aquecimento no norte e calor úmido extremo no sul podem ocorrer.",
    impactoNasChuvas: "Padrões irregulares; redução no norte, excesso no sul.",
    confianca: "Moderada",
    lat: 9.08, lng: 8.68,
  },
  {
    id: "KE",
    nome: "Quênia",
    continente: "África",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño traz chuvas intensas ao Quênia, após anos de seca, causando enchentes devastadoras.",
    impactoDoElNino: "Chuvas torrenciais; enchentes massivas; deslizamentos de terra; surtos de doenças transmitidas pela água.",
    regioesAfetadas: "Rift Valley, Costa, Nairobi, Norte do Quênia",
    ameacas: ["enchentes", "chuva intensa"],
    impactoNaAgricultura: "Paradoxal: alívio da seca mas danos por excesso de chuvas; perda de gado em enchentes.",
    impactoNaAgua: "Excesso de água causa contaminação; enchentes destroem infraestrutura hídrica.",
    impactoNaTemperatura: "Temperaturas mais amenas durante chuvas intensas.",
    impactoNasChuvas: "As chuvas de outubro a dezembro podem aumentar de forma expressiva.",
    confianca: "Alta",
    lat: -0.02, lng: 37.91,
  },
  {
    id: "GB",
    nome: "Reino Unido",
    continente: "Europa",
    nivelDeRisco: "baixo",
    resumoClimatico: "El Niño tem impacto limitado e indireto no Reino Unido, principalmente através de mudanças no jet stream.",
    impactoDoElNino: "Invernos potencialmente mais amenos e úmidos; verões mais frescos; impacto sutil nas temperaturas.",
    regioesAfetadas: "Inglaterra, Escócia, País de Gales",
    ameacas: ["chuva intensa"],
    impactoNaAgricultura: "Impacto mínimo; possível excesso de umidade em algumas regiões.",
    impactoNaAgua: "Geralmente adequado; possível aumento de chuvas no inverno.",
    impactoNaTemperatura: "Invernos ligeiramente mais amenos podem ocorrer.",
    impactoNasChuvas: "Ligeiro aumento no inverno; impacto pouco significativo.",
    confianca: "Baixa",
    lat: 55.38, lng: -3.44,
  },
  {
    id: "FR",
    nome: "França",
    continente: "Europa",
    nivelDeRisco: "baixo",
    resumoClimatico: "El Niño tem impacto limitado na França, com efeitos sutis no clima de inverno.",
    impactoDoElNino: "Invernos ligeiramente mais amenos; mudanças sutis nos padrões de precipitação; impacto mínimo geral.",
    regioesAfetadas: "Sul da França, Paris, Costa Atlântica",
    ameacas: ["calor"],
    impactoNaAgricultura: "Impacto mínimo direto; possíveis ondas de calor no verão em combinação com mudanças climáticas.",
    impactoNaAgua: "Sem impacto significativo direto.",
    impactoNaTemperatura: "Variações térmicas pequenas e efeitos indiretos podem ocorrer.",
    impactoNasChuvas: "Mudanças mínimas e não significativas.",
    confianca: "Baixa",
    lat: 46.23, lng: 2.21,
  },
  {
    id: "DE",
    nome: "Alemanha",
    continente: "Europa",
    nivelDeRisco: "baixo",
    resumoClimatico: "El Niño tem impacto mínimo na Alemanha, com efeitos indiretos possíveis.",
    impactoDoElNino: "Invernos potencialmente mais amenos; efeito indireto através do jet stream do Atlântico Norte.",
    regioesAfetadas: "Baviera, Norte da Alemanha",
    ameacas: ["calor"],
    impactoNaAgricultura: "Impacto negligenciável direto; possíveis ondas de calor no verão.",
    impactoNaAgua: "Sem impacto direto significativo.",
    impactoNaTemperatura: "Variações pequenas e invernos ligeiramente mais amenos podem ocorrer.",
    impactoNasChuvas: "Sem padrão significativo relacionado ao El Niño.",
    confianca: "Baixa",
    lat: 51.17, lng: 10.45,
  },
  {
    id: "ES",
    nome: "Espanha",
    continente: "Europa",
    nivelDeRisco: "moderado",
    resumoClimatico: "El Niño pode trazer invernos mais secos ao sul da Espanha, agravando a seca existente.",
    impactoDoElNino: "Invernos mais secos no sul; possível agravamento da seca mediterrânea; ondas de calor mais intensas no verão.",
    regioesAfetadas: "Andaluzia, Catalunha, Ilhas Canárias, Costa Mediterrânea",
    ameacas: ["seca", "calor", "agricultura"],
    impactoNaAgricultura: "Estresse hídrico em olivais e vinhedos; redução na produção de azeite.",
    impactoNaAgua: "Agravamento da crise hídrica no sul; reservatórios já em níveis baixos.",
    impactoNaTemperatura: "Verões mais quentes; ondas de calor mais longas.",
    impactoNasChuvas: "Redução moderada das chuvas pode ocorrer no sul e leste.",
    confianca: "Moderada",
    lat: 40.46, lng: -3.75,
  },
  {
    id: "IT",
    nome: "Itália",
    continente: "Europa",
    nivelDeRisco: "moderado",
    resumoClimatico: "El Niño pode intensificar condições secas no sul da Itália e Sicília.",
    impactoDoElNino: "Seca no sul; ondas de calor mais intensas; possível impacto na agricultura mediterrânea.",
    regioesAfetadas: "Sicília, Sardenha, Sul da Itália, Vale do Pó",
    ameacas: ["seca", "calor", "agricultura"],
    impactoNaAgricultura: "Estresse em olivais e vinhedos; redução na produção de trigo duro no sul.",
    impactoNaAgua: "Pressão sobre recursos hídricos no sul; Rio Pó com níveis baixos.",
    impactoNaTemperatura: "Verões mais quentes podem ocorrer no sul.",
    impactoNasChuvas: "Redução moderada no sul e ilhas.",
    confianca: "Moderada",
    lat: 41.87, lng: 12.57,
  },
  {
    id: "RU",
    nome: "Rússia",
    continente: "Europa/Ásia",
    nivelDeRisco: "baixo",
    resumoClimatico: "El Niño tem impacto limitado na Rússia, com efeitos regionais variáveis.",
    impactoDoElNino: "Invernos mais amenos no oeste; possíveis ondas de calor no verão; impacto variável na Sibéria.",
    regioesAfetadas: "Rússia Europeia, Sibéria, Extremo Oriente",
    ameacas: ["calor", "queimadas"],
    impactoNaAgricultura: "Possíveis ondas de calor afetando trigo no sul da Rússia; incêndios florestais na Sibéria.",
    impactoNaAgua: "Impacto limitado; derretimento acelerado de neve na primavera.",
    impactoNaTemperatura: "Invernos mais amenos no oeste; verões variáveis.",
    impactoNasChuvas: "Padrões variáveis sem sinal forte de El Niño.",
    confianca: "Baixa",
    lat: 61.52, lng: 105.32,
  },
  {
    id: "SA",
    nome: "Arábia Saudita",
    continente: "Ásia",
    nivelDeRisco: "moderado",
    resumoClimatico: "El Niño pode trazer chuvas incomuns ao deserto saudita e intensificar ondas de calor.",
    impactoDoElNino: "Chuvas incomuns no deserto; enchentes relâmpago; ondas de calor extremas; tempestades de areia.",
    regioesAfetadas: "Riad, Jeddah, Região Oriental, Deserto de Rub' al Khali",
    ameacas: ["calor", "enchentes", "chuva intensa"],
    impactoNaAgricultura: "Impacto em culturas irrigadas; estresse térmico; chuvas incomuns podem danificar infraestrutura agrícola.",
    impactoNaAgua: "Enchentes relâmpago em áreas urbanas; infraestrutura não preparada para chuvas intensas.",
    impactoNaTemperatura: "Calor extremo e prolongado pode ocorrer.",
    impactoNasChuvas: "Possível aumento de chuvas torrenciais esporádicas.",
    confianca: "Baixa",
    lat: 23.89, lng: 45.08,
  },
  {
    id: "PK",
    nome: "Paquistão",
    continente: "Ásia",
    nivelDeRisco: "extremo",
    resumoClimatico: "El Niño pode tanto intensificar ondas de calor quanto alterar padrões de monção no Paquistão.",
    impactoDoElNino: "Ondas de calor letais; monção alterada; enchentes devastadoras; crise humanitária potencial.",
    regioesAfetadas: "Sindh, Punjab, Baluchistão, KPK",
    ameacas: ["calor", "enchentes", "seca", "agricultura"],
    impactoNaAgricultura: "Destruição de safras de algodão e trigo; perda de gado; insegurança alimentar.",
    impactoNaAgua: "Enchentes devastadoras em anos de monção forte; seca em outros períodos; contaminação da água.",
    impactoNaTemperatura: "Ondas de calor extremas podem elevar riscos graves à saúde.",
    impactoNasChuvas: "Padrão variável: pode ter chuvas extremas ou déficit hídrico.",
    confianca: "Moderada",
    lat: 30.38, lng: 69.35,
  },
  {
    id: "BD",
    nome: "Bangladesh",
    continente: "Ásia",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño pode enfraquecer a monção em Bangladesh, mas o país permanece vulnerável a enchentes.",
    impactoDoElNino: "Monção potencialmente mais fraca; risco de seca; mas enchentes costeiras permanentes; ciclones.",
    regioesAfetadas: "Delta do Ganges, Dhaka, Costa Sul, Sylhet",
    ameacas: ["enchentes", "seca", "agricultura", "calor"],
    impactoNaAgricultura: "Impacto severo no arroz; perda de safras por seca ou enchentes; insegurança alimentar.",
    impactoNaAgua: "Salinização de aquíferos costeiros; enchentes no delta; contaminação.",
    impactoNaTemperatura: "Ondas de calor mais intensas; calor úmido letal.",
    impactoNasChuvas: "Monção potencialmente mais fraca mas enchentes costeiras persistentes.",
    confianca: "Moderada",
    lat: 23.68, lng: 90.36,
  },
  {
    id: "TH",
    nome: "Tailândia",
    continente: "Ásia",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño causa seca significativa na Tailândia, afetando a produção de arroz.",
    impactoDoElNino: "Seca severa; redução da monção; crise na produção de arroz; incêndios florestais no norte.",
    regioesAfetadas: "Nordeste (Isan), Norte, Bangkok, Central",
    ameacas: ["seca", "agricultura", "queimadas", "calor"],
    impactoNaAgricultura: "Arroz e cana-de-açúcar podem sofrer perdas, com maior pressão sobre a irrigação.",
    impactoNaAgua: "Reservatórios em níveis mínimos; racionamento em Bangkok; rios principais com níveis baixos.",
    impactoNaTemperatura: "Calor extremo pode ocorrer em Bangkok e nas planícies centrais.",
    impactoNasChuvas: "A temporada de monção pode apresentar redução relevante.",
    confianca: "Alta",
    lat: 15.87, lng: 100.99,
  },
  {
    id: "VN",
    nome: "Vietnã",
    continente: "Ásia",
    nivelDeRisco: "alto",
    resumoClimatico: "El Niño causa seca no sul do Vietnã e afeta severamente o Delta do Mekong.",
    impactoDoElNino: "Seca no delta do Mekong; salinização de rios; perda de safras de arroz; escassez de água potável.",
    regioesAfetadas: "Delta do Mekong, Planalto Central, Costa Central, Hanói",
    ameacas: ["seca", "agricultura", "calor"],
    impactoNaAgricultura: "Perda severa na produção de arroz no Mekong; salinização destrói plantações; impacto em café e pimenta.",
    impactoNaAgua: "Salinização do Mekong; falta de água doce; reservatórios baixos.",
    impactoNaTemperatura: "Temperaturas acima da média e ondas de calor mais frequentes podem ocorrer.",
    impactoNasChuvas: "Redução expressiva das chuvas pode ocorrer no sul.",
    confianca: "Alta",
    lat: 14.06, lng: 108.28,
  },
];

export const quizQuestions = [
  {
    question: "O que é o El Niño?",
    options: [
      "Um tipo de furacão que atinge a América do Sul",
      "O aquecimento anormal das águas do Oceano Pacífico Equatorial",
      "Uma corrente de ar frio que vem do Polo Norte",
      "Um terremoto submarino no Pacífico"
    ],
    correct: 1,
    explanation: "O El Niño é um fenômeno climático caracterizado pelo aquecimento anormal das águas superficiais do Oceano Pacífico Equatorial, especialmente na região próxima à costa do Peru. Esse aquecimento altera padrões de circulação atmosférica globalmente."
  },
  {
    question: "Qual a diferença principal entre El Niño e La Niña?",
    options: [
      "El Niño ocorre no Atlântico e La Niña no Pacífico",
      "El Niño aquece as águas do Pacífico e La Niña as resfria",
      "El Niño causa frio global e La Niña causa calor",
      "Não há diferença, são o mesmo fenômeno"
    ],
    correct: 1,
    explanation: "El Niño é o aquecimento anormal das águas do Pacífico Equatorial, enquanto La Niña é o resfriamento anormal dessas mesmas águas. Ambos fazem parte do ciclo ENSO (El Niño-Southern Oscillation) e têm efeitos climáticos opostos em muitas regiões."
  },
  {
    question: "Qual região do mundo é mais diretamente afetada pelo El Niño?",
    options: [
      "Europa Ocidental",
      "Costa oeste da América do Sul e Oceano Pacífico",
      "Polo Norte",
      "Deserto do Saara"
    ],
    correct: 1,
    explanation: "A costa oeste da América do Sul (especialmente Peru e Equador) e as ilhas do Pacífico são as regiões mais diretamente afetadas. O fenômeno recebeu o nome 'El Niño' (O Menino, em espanhol) de pescadores peruanos que notavam o aquecimento das águas ao redor do Natal."
  },
  {
    question: "Como o El Niño afeta o Brasil?",
    options: [
      "Causa neve em todo o país",
      "Traz seca no Norte/Nordeste e chuvas excessivas no Sul",
      "Não tem nenhum efeito no Brasil",
      "Causa tsunamis na costa brasileira"
    ],
    correct: 1,
    explanation: "No Brasil, o El Niño tipicamente causa seca severa no Norte e Nordeste (incluindo a Amazônia) e chuvas excessivas no Sul. Isso pode levar a incêndios florestais na Amazônia e enchentes no Rio Grande do Sul, por exemplo."
  },
  {
    question: "O que significa ENSO?",
    options: [
      "European Natural Storm Organization",
      "El Niño-Southern Oscillation (Oscilação Sul do El Niño)",
      "Equatorial Northern Storm Occurrence",
      "Environmental Nature Safety Organization"
    ],
    correct: 1,
    explanation: "ENSO significa El Niño-Southern Oscillation (Oscilação Sul do El Niño). É o termo científico que engloba os três estados do fenômeno: El Niño (fase quente), La Niña (fase fria) e Neutro. O ENSO é um dos principais drivers do clima global."
  }
];

export const timelineEvents = [
  {
    phase: "Condições Normais",
    icon: "Waves",
    description: "Ventos alísios sopram de leste para oeste no Pacífico, mantendo águas quentes na região da Indonésia e águas frias na costa da América do Sul.",
    color: "primary",
  },
  {
    phase: "Desenvolvimento",
    icon: "Thermometer",
    description: "Os ventos alísios enfraquecem e as águas quentes começam a se mover para leste. A temperatura da superfície do mar começa a subir na região central e leste do Pacífico.",
    color: "chart-5",
  },
  {
    phase: "Pico do El Niño",
    icon: "Flame",
    description: "As águas do Pacífico Equatorial atingem forte aquecimento. Impactos climáticos globais podem se intensificar, incluindo secas, enchentes e ondas de calor.",
    color: "destructive",
  },
  {
    phase: "Enfraquecimento",
    icon: "TrendingDown",
    description: "As águas começam a esfriar gradualmente. Os padrões climáticos começam a retornar ao normal, mas impactos residuais podem persistir por meses.",
    color: "accent",
  },
  {
    phase: "Transição",
    icon: "RefreshCw",
    description: "O sistema pode voltar a condições neutras ou transicionar para La Niña (resfriamento). Todo o ciclo pode durar de 12 a 18 meses.",
    color: "chart-2",
  },
];

export const riskColors = {
  baixo: "#22c55e",
  moderado: "#eab308",
  alto: "#f97316",
  extremo: "#ef4444",
};

export const riskLabels = {
  baixo: "Baixo",
  moderado: "Moderado",
  alto: "Alto",
  extremo: "Extremo",
};

export const threatLabels = {
  seca: "Seca",
  enchentes: "Enchentes",
  calor: "Calor Extremo",
  agricultura: "Perdas Agrícolas",
  queimadas: "Queimadas",
  "chuva intensa": "Chuva Intensa",
};

export const threatIcons = {
  seca: "Droplets",
  enchentes: "CloudRain",
  calor: "Thermometer",
  agricultura: "Wheat",
  queimadas: "Flame",
  "chuva intensa": "CloudLightning",
};